### ISSUE TITLE
Files uploaded to experiment not available

### ISSUE THREAD

**Issue by timvgl** [elabftw/elabapy#37] opened 2023-01-24 17:53 UTC
Hi together,
currently I am using version 4.4.3 of eLab and the API Python Version 1.
Unfortunately, I am not able to download the files (which are small json files) attached to the experiment using the API.
I have tested the code using your demo and it worked fine.
In the browserinterface all files are available.
This is the errormessage:

`Traceback (most recent call last):`
 `File "C:***\bugfix.py", line 8, in <module>`
`            manager.get_upload(123)`
 `File "C:\***\elabapy\Manager.py", line 71, in get_upload`
`            return self.send_req("uploads/" + str(id), verb='GET', binary=True)`
 `File "C:\***\elabapy\baseapi.py", line 85, in send_req`
`            req.raise_for_status()`
  `File "C:\***\requests\models.py", line 1021, in raise_for_status`
`            raise HTTPError(http_error_msg, response=self)`
  `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: ***/api/v1/uploads/123`

All other operations are working fine with the chosen token and endpoint.
Thank you for your help
Yours faithfully 
Tim Vogel

**Comment by NicolasCARPi** [comment] 2023-01-24 21:41
What do you get if you use CURL? (or directly in the browser it works too!)

Also, when you report something like this, it helps to provide a reproducible bug with a code snippet that shows the error you have. Sometimes, the error is in the client code. In my hands this works:

~~~
print(manager.get_upload(99))
~~~

And it prints the content of the file (a json file here).

**Comment by timvgl** [comment] 2023-01-25 10:06
With curl: {"result":"Nothing to show with this id"}. In the browser using the API link it is the same.
Attached, you will find the code and the error message.
Currently, this is a general problem. I cannot download any files linked to experiments via the API - it does not matter if I create new experiments or use the old ones.
![error elab api](https://user-images.githubusercontent.com/97906175/214535196-1d7221ba-ed79-4aa5-8b17-4d79db2d57bb.PNG)

**Comment by NicolasCARPi** [comment] 2023-01-25 12:23
Another user reported the exact same issue today. But I cannot reproduce it locally. It all works well and that part of the code hasn't really been touched for quite some time. I've tried on 4.4.3 and the current dev version (4.5.0-beta3). `elabapy` is 1.0.0.

Are you by any chance at uni-kl?

**Comment by timvgl** [comment] 2023-01-25 12:30
Yes I am.

**Comment by NicolasCARPi** [comment] 2023-01-25 13:00
Then I believe it is an issue on your end, not in elabapy, as the other user is also in uni-kl. Can you download the file through the web interface by clicking its name?

**Comment by timvgl** [comment] 2023-01-25 13:04
Yes, I can download the file using the webinterface.

**Comment by NicolasCARPi** [comment] 2023-01-25 13:38
Can you try with apiv2? See: https://github.com/elabftw/elabapi-python/blob/e059220cbe37169eb8702ec76aa77e424e4cce08/examples/03.py#L45

Just to see if it is an apiv1 specific issue or an api specific issue.

**Comment by timvgl** [comment] 2023-01-25 13:51
Yes with API v2 it works. Just a sidequestion - will API v2 remain like that, or are you planning to do major changes?

**Comment by NicolasCARPi** [comment] 2023-01-25 13:56
I think api2 is quite stable now. The changes will only be small fixes so it is safe and recommended to start using it, because at some point apiv1 will disappear!

**Comment by NicolasCARPi** [comment] 2023-01-26 02:11
Given that this seems to be an issue visible only in your context and only in apiv1, curl or python. I'll close this as wontfix.

api v1 will get deprecated, so it's a good idea to move to api v2 as soon as possible.

**Closed as completed by NicolasCARPi** 2023-01-26 02:11 UTC
Labels: invalid
